services:
  - type: web
    name: telabombeiros
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: STUN_URLS
        value: stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302
      - key: TURN_URLS
        sync: false
      - key: TURN_SECRET
        sync: false
      - key: TURN_USERNAME
        sync: false
      - key: TURN_CREDENTIAL
        sync: false
